### ISSUE TITLE
add DNS challenge support

### ISSUE THREAD

**Issue by ehaselwanter** [schubergphilis/chef-acme#51] opened 2016-10-29 06:42 UTC
for private network servers it would be cool to add the DNS challenge support. ideas on the implementation could be drawn from https://github.com/lukas2511/dehydrated

**Comment by rmoriz** [comment] 2016-11-03 12:00
sounds like managing DNS records in chef => chef-provisioning?

**Comment by ehaselwanter** [comment] 2016-11-03 12:43
yes and no. so for this part it would be using the dns challenge. you can use it if your TLS endpoint is on a private network, but DNS is public (dnsimple/rout53).

and yes. maybe you use https://github.com/dnsimple/chef-dnsimple for managing the DNS record itself, but that is not what this issue is about.

**Comment by rmoriz** [comment] 2016-11-03 13:32
The DNS challenge changes over time, this is not a one-time thing. So in all cases you need automation with DNS / cloud-services. related: https://github.com/paybyphone/terraform-provider-acme

**Comment by ehaselwanter** [comment] 2016-11-03 16:33
well. the gem you are using does support it. so I just wanted to mention that you can improve on the options. 

- https://github.com/unixcharles/acme-client/blob/master/README.md#authorize-for-domain

>  This example is using the http-01 challenge type. Other challenges are dns-01 or tls-sni-01.
challenge = authorization.http01

relevant part in the code here:

- https://github.com/schubergphilis/chef-acme/blob/78591b0988472fbde989e2b93a3036b67059b748/providers/certificate.rb#L62

the prerequisites to the challenge (the dns record itself) can be done to the users liking. be it with a cookbook/recipe, terraform, ...

**Comment by axos88** [comment] 2016-12-05 15:18
#54 may be a good starting point. Just add your own provider that can provide DNS challanges
Still a WIP, but comments are welcome.

**Comment by ehaselwanter** [comment] 2017-01-25 16:06
looks like a good entry point. for the time being I switched to caddy which supports it out of the box.

**Comment by elthariel** [comment] 2017-04-11 11:57
Sidenote: I've a cookbook to manage bind and generate zone files it might be another lead:

https://github.com/elthariel/cookbook-named

**Comment by axos88** [comment] 2017-05-12 07:01
FYI: #75 has been merged. It was intended as a method for tls-sni challanges, but with a little refactoring it can be extended to be able to define more generalized setup / teardown methods, and to support other challanges as well.

**Comment by elachlan** [comment] 2020-07-14 01:28
This would be fantastic as it would enable DNS Authentication downstream for Gitlab (https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/3209)

**Closed** 2021-07-08 12:27 UTC
